# Generated by Django 5.1.3 on 2024-12-22 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_delete_admin_user_is_admin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="create_time",
            new_name="timestamp",
        ),
        migrations.CreateModel(
            name="ImageUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(max_length=255, upload_to="uploads/%Y/%m/%d/"),
                ),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待检测"),
                            ("completed", "检测完成"),
                            ("failed", "检测失败"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.TextField(
                        blank=True, help_text="检测结果的描述，或者以JSON字符串存储", null=True
                    ),
                ),
                (
                    "review",
                    models.TextField(blank=True, help_text="管理员或用户的评论或反馈", null=True),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("upload", "图片上传"),
                            ("view_result", "查看检测结果"),
                            ("add_review", "添加评论"),
                            ("admin_action", "管理员操作"),
                        ],
                        help_text="用户执行的操作类型",
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "detail",
                    models.TextField(blank=True, help_text="操作的详细描述或补充信息", null=True),
                ),
                (
                    "imageid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="api.imageupload",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
