# Generated by Django 5.1.3 on 2024-12-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_rename_create_time_user_timestamp_imageupload_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="action",
            field=models.CharField(
                choices=[
                    ("register", "注册"),
                    ("login", "登录"),
                    ("upload", "图片上传"),
                    ("view_result", "查看检测结果"),
                    ("add_review", "添加评论"),
                    ("admin_action", "管理员操作"),
                ],
                help_text="用户执行的操作类型",
                max_length=50,
            ),
        ),
    ]
