# Generated by Django 5.1.3 on 2024-12-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
